### ISSUE TITLE
How to use ? what does it do ?

### ISSUE THREAD

**Issue by KNOWPEIN** [Dragovorn/courier#6]
Hi
I am trying to understand Dota2 gsi
wonder what your app does ?

**Comment by Dragovorn** [comment]
What is it that you're wondering about Dota 2 GSI?

Because courier takes information it gets from GSI then relays some of it to Discord to create a Rich Presence with that information.

**Comment by KNOWPEIN** [comment]
i am looking for specific information from GSI like .... list of buffs that hero is affected currently and relay them...

**Comment by Dragovorn** [comment]
I'm not 100% certain if you can get that information, the data that you get from GSI can be found here https://github.com/antonpup/Dota2GSI#layout the format is JSON.

The best way to figure out if GSI has the information you require is to setup a basic application and just dump all the data that GSI gives you into a log file and look through it to see the data you are getting.
